# Generated by Django 3.0.4 on 2020-09-08 22:23

from django.db import migrations, models
import myapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='model_pic',
            field=models.ImageField(default='none/no-img.jpg', max_length=4096, storage=myapp.storage.OverwriteStorage(), upload_to=''),
        ),
    ]
